<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BarangSatuanRecord extends TActiveRecord
{
	const TABLE='tbm_satuan_barang';

	public $id;
	public $id_barang;
	public $id_satuan;
	public $jumlah;
	public $urutan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
