<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BarangRecord extends TActiveRecord
{
	const TABLE='tbm_barang';

	public $id;
	public $kode_barang;
	public $nama;
	public $kelompok_id;
	public $kategori_id;
	public $min_stock;
	public $max_stock;
	public $max_beli_bulanan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
