<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BayarRekapGajiRecord extends TActiveRecord
{
	const TABLE='tbt_bayar_rekap_gaji';

	public $id;
	public $no_pembayaran;
	public $tgl_pembayaran;
	public $id_rekap;
	public $total_gaji_dibayarkan;
	public $user;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
