<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BayarTbsOrderDetailRecord extends TActiveRecord
{
	const TABLE='tbt_pembayaran_tbs_detail';

	public $id;
	public $id_pembayaran;
	public $id_tbs_order;
	public $netto_1;
	public $jumlah_bongkar;
	public $subtotal_spsi;
	public $netto_2;
	public $harga;
	public $subtotal_tbs;
	public $fee;
	public $subtotal_fee;
	public $ppn;
	public $pph;
	public $total_tbs_order;
	public $deleted;



	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
