<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BayarTbsOrderRecord extends TActiveRecord
{
	const TABLE='tbt_pembayaran_tbs';

	public $id;
	public $id_tbs_order;
	public $no_pembayaran;
	public $tgl_pembayaran;
	public $wkt_pembayaran;
	public $jumlah_pembayaran;
	public $id_coa;
	public $jns_bayar;
	public $id_bank;
	public $no_ref;
	public $deleted;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
