<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class CetakanRecord extends TActiveRecord
{
	const TABLE='tbt_cetakan';

	public $id;
	public $jns_transaksi;
	public $id_pelanggan;
	public $nama_pelanggan;
	public $tgl_transaksi;
	public $wkt_transaksi;
	public $subtotal;
	public $diskon;
	public $total;
	public $st_lunas;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
