<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class CetakanBayarRecord extends TActiveRecord
{
	const TABLE='tbt_cetakan_bayar';

	public $id;
	public $id_transaksi;
	public $tgl_bayar;
	public $wkt_bayar;
	public $jml_bayar;
	public $kembalian;
	public $sisa_bayar;
	public $st_dp;
	public $st_posting;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
