<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class CoaRecord extends TActiveRecord
{
	const TABLE='tbm_coa';

	public $id;
	public $id_group_coa;
	public $kode_coa;
	public $group_type;
	public $nama;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
