<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class CommodityTransactionRecord extends TActiveRecord
{
	const TABLE='tbt_commodity_transaction';

	public $id;
	public $transaction_no;
	public $tgl_transaksi;
	public $jns_kontrak;
	public $id_kontrak;
	public $pembeli;
	public $alamat_pembeli;
	public $npwp;
	public $commodity_type;
	public $berat_kendaraan;
	public $berat_kendaraan_isi;
	public $jumlah_commodity;
	public $id_satuan;
	public $harga;
	public $total;
	public $status;
	public $deleted;

	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
