<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class DepartmentRecord extends TActiveRecord
{
	const TABLE='tbm_department';

	public $id;
	public $id_parent;
	public $nama;
	public $kode;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
