<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ExpenseKaryawanRecord extends TActiveRecord
{
	const TABLE='tbt_expense_karyawan';

	public $id;
	public $id_karyawan;
	public $tgl;
	public $jns_expense;
	public $jml_expense;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
