<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class GolonganKaryawanRecord extends TActiveRecord
{
	const TABLE='tbm_golongan_karyawan';

	public $id;
	
	public $nama;
	public $gaji_pokok;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
