<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class GroupCoaRecord extends TActiveRecord
{
	const TABLE='tbm_coa_kodrek_group';

	public $id;
	public $kode_group;
	public $nama;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
