<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class HargaTbsOrderRecord extends TActiveRecord
{
	const TABLE='tbt_harga_tbs_order';

	public $id;
	public $tgl_transaksi;
	public $id_komidel;
	public $id_barang;
	public $id_kategori_harga;
	public $harga;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
