<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class JabatanRecord extends TActiveRecord
{
	const TABLE='tbm_jabatan';

	public $id;
	
	public $id_department;
	public $id_subdepartment;
	public $nama;
	public $kode;
	public $kuota;
	public $id_level_distribusi;
	public $jatah_cuti;
	public $tunjangan_jabatan;
	public $tunjangan_komunikasi;
	public $premi_karyawan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
