<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class JadwalRecord extends TActiveRecord
{
	const TABLE='tbm_jadwal';

	public $id;
	public $idcab;
	public $idkaryawan;
	public $tanggal;
	public $shif;
	public $istirahat;
	public $awal;
	public $ahir;
	public $lama;
	public $tglbuat;
	public $jambuat;
	public $operator;
	public $opabsen;
	public $tglupdate;
	public $jamupdate;
	public $datang;
	public $pulang;
	public $kodetelat;
	public $kodepulangawal;
	public $kodelembur;
	public $alpa;
	public $ijin;
	public $cuti;
	public $statuslembur;
	public $kodecuti;
	public $aktif;
	public $libur;
	public $dinas;
	public $st_hadir;
	public $st;
	public $st_telat;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
