<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class JadwalPenaltyRecord extends TActiveRecord
{
	const TABLE='tbm_jadwal_penalty';

	public $id;
	public $idjadwal;
	public $payroll_id;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
