<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class JenisKendaraanRecord extends TActiveRecord
{
	const TABLE='tbm_jenis_kendaraan';

	public $id;
	public $jenis_kendaraan;
	public $jenis_bongkar;
	public $jumlah_bongkar;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
