<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class KantorCabangRecord extends TActiveRecord
{
	const TABLE='tbm_cabang';

	public $id;
	public $nama;
	public $alamat;
	public $id_kota;
	public $telp;
	public $email;
	public $nama_kontak;
	public $pendapatan;
	public $umk;
	public $ump;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
