<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class KaryawanRecord extends TActiveRecord
{
	const TABLE='tbm_karyawan';

	public $id;
	
	public $id_cabang;
	public $id_jabatan;
	public $id_golongan;
	public $id_ptkp;
	public $nik;
	public $ktp;
	public $nama;
	public $jkel;
	public $tmplahir;
	public $tgllahir;
	public $alamat;
	public $id_kota;
	public $status_kawin;
	public $id_agama;
	public $umur;
	public $id_pendidikan;
	public $telp;
	public $tglawalkerja;
	public $aktif;
	public $status_karyawan;
	public $id_bank;
	public $norek;
	public $masakerja;
	public $harimasakerja;
	public $loyalty;
	public $posisi_dinas;
	public $tunjangan_natura;
	public $st_bpjs_kesehatan;
	public $st_bpjs_ketenagakerjaan;
	public $tambahan_keluarga;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
