<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class KomidelRecord extends TActiveRecord
{
	const TABLE='tbm_setting_komidel';

	public $id;
	public $operator;
	public $komidel;
	public $harga;
	public $nama;
	public $singkatan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
