<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class LemburRecord extends TActiveRecord
{
	const TABLE='tbm_lembur';

	public $id;
	public $id_karyawan;
	public $id_jadwal;
	public $lama_lembur;
	public $tgl_lembur;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
