<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class LevelDistribusiRecord extends TActiveRecord
{
	const TABLE='tbm_level_distribusi';

	public $id;
	public $kode;
	public $nilai;
	public $bpjs_distribusi;
	public $dinas_distribusi;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
