<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MasterCetakanDetailBahanRecord extends TActiveRecord
{
	const TABLE='tbm_cetakan_detail_bahan';

	public $id;
	public $id_cetakan;
	public $id_barang;
	public $ukuran;
	public $harga;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
