<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MasterCetakanRecord extends TActiveRecord
{
	const TABLE='tbm_cetakan';

	public $id;
	public $nama_cetakan;
	public $kategori_cetakan;
	public $jns_tinta;
	public $hrg_tinta;
	public $jns_laminasi;
	public $hrg_laminasi;
	
	public $total_bahan;
	public $total_param;
	public $total_modal;
	public $total_persen;
	public $subtotal;
	public $total_harga_jual;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
