<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MasterCetakanDetailParamRecord extends TActiveRecord
{
	const TABLE='tbm_cetakan_detail_param';

	public $id;
	public $id_cetakan;
	public $parameter;
	public $harga;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
