<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MenuRecord extends TActiveRecord
{
	const TABLE='tbm_menu';

	public $id;
	public $parent_id;
	public $nama;
	public $link;
	public $icon;
	public $aktif;
	public $urutan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
