<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MutasiKasRecord extends TActiveRecord
{
	const TABLE='tbt_mutasi_kas';

	public $id;
	public $tgl_transaksi;
	public $no_referensi;
	public $id_bank_asal;
	public $id_bank_tujuan;
	public $deskripsi;
	public $jumlah_mutasi;
	public $biaya_admin;
	public $total_mutasi;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
