<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MutasiBarangDetailRecord extends TActiveRecord
{
	const TABLE='tbt_mutasi_barang_detail';

	public $id;
	public $id_transaksi;
	public $id_barang;
	public $id_satuan;
	public $jml;
	public $jns_keluar;
	public $st_asset;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
