<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class MutasiBarangRecord extends TActiveRecord
{
	const TABLE='tbt_mutasi_barang';

	public $id;
	public $tgl_transaksi;
	public $wkt_transaksi;
	public $jumlah_barang;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
