<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PayrollRecord extends TActiveRecord
{
	const TABLE='tbm_payrol';

	public $id;
	public $kategori;
	public $subkategori;
	public $attendance_id;
	public $time1;
	public $time2;
	public $globaldistribusi;
	public $distribusi;
	public $ket;
	public $urut;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
