<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PayrollFormulaRecord extends TActiveRecord
{
	const TABLE='tbm_payroll_formula';

	public $id;
	public $payroll_id;
	public $parameter_id;
	public $operator_id;
	public $order_id;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
