<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PelangganRecord extends TActiveRecord
{
	const TABLE='tbm_pelanggan';

	public $id;
	public $kategori_id;
	public $nama;
	public $alamat;
	public $telepon;
	public $npwp;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
