<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PemasokRecord extends TActiveRecord
{
	const TABLE='tbm_pemasok';

	public $id;
	public $kategori_id;
	public $nama;
	public $alamat;
	public $telepon;
	public $fax;
	public $contact_person;
	public $fee;
	public $no_sp;
	public $id_kategori_harga;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
