<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PemasokBarangRecord extends TActiveRecord
{
	const TABLE='tbd_pemasok_barang';

	public $id;
	public $id_barang;
	public $id_pemasok;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
