<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PembelianRecord extends TActiveRecord
{
	const TABLE='tbt_pembelian';

	public $id;
	public $id_pemasok;
	public $tgl_transaksi;
	public $wkt_transaksi;
	public $st_posting;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
