<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PembelianDetailRecord extends TActiveRecord
{
	const TABLE='tbt_pembelian_detail';

	public $id;
	public $id_transaksi;
	public $id_barang;
	public $jml;
	public $id_harga;
	public $harga;
	public $total;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
