<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PenerimaanPenjualanRecord extends TActiveRecord
{
	const TABLE='tbt_penerimaan_penjualan';

	public $id;
	public $id_penjualan;
	public $tgl_penerimaan;
	public $bruto_diterima;
	public $tarra_diterima;
	public $netto_diterima;
	public $ffa_diterima;
	public $dobi_diterima;
	public $mi_diterima;
	public $jumlah_dikirim;
	public $jumlah_diterima;
	public $jumlah_susut;
	public $harga;
	public $total_penjualan;
	public $deleted;



	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
