<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PenerimaanPenjualanRecord extends TActiveRecord
{
	const TABLE='tbt_penerimaan_penjualan';

	public $id;
	public $id_kontrak;
	public $tgl_penerimaan;
	public $wkt_penerimaan;
	public $total_penjualan;
	public $total_penerimaan;
	public $id_coa;
	public $jns_bayar;
	public $id_bank;
	public $no_ref;
	public $deleted;



	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
