<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PenyesuaianDetailRecord extends TActiveRecord
{
	const TABLE='tbt_penyesuaian_detail';

	public $id;
	public $id_penyesuaian;
	public $kelompok_akun;
	public $jenis_saldo;
	public $asal_saldo;
	public $nama_akun;
	public $nilai_akun;
	public $keterangan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
