<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PenyusutanAktivaTetapRecord extends TActiveRecord
{
	const TABLE='tbd_penyusutan_aktiva';

	public $id;
	public $id_aktiva;
	public $tahun_ke;
	public $tahun;
	public $jml_bulan;
	public $nilai_penyusutan;
	public $nilai_aktiva;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
