<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PerusahaanRecord extends TActiveRecord
{
	const TABLE='tbd_perusahaan';

	public $id;
	public $nama;
	public $username_pemilik;
	public $alamat;
	public $telepon;
	public $email;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
