<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ProduksiBarangRecord extends TActiveRecord
{
	const TABLE='tbt_processing_product';

	public $id;
	public $processing_no;
	public $tgl_processing;
	public $id_tbs;
	public $id_satuan_tbs;
	public $processing_qty;
	public $cpo_qty;
	public $id_satuan_cpo;
	public $pk_qty;
	public $id_satuan_pk;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
