<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PurchaseOrderDetailRecord extends TActiveRecord
{
	const TABLE='tbt_purchase_order_detail';

	public $id;
	public $status;
	public $id_po;
	public $id_ro_detail;
	public $id_barang;
	public $id_satuan;
	public $jumlah;
	public $jumlah_diterima;
	public $harga_satuan_besar;
	public $harga_satuan;
	public $discount;
	public $subtotal;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
