<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class PurchaseOrderBiayaLainRecord extends TActiveRecord
{
	const TABLE='tbt_purchase_order_biaya_lain';

	public $id;
	public $id_po;
	public $nama_biaya;
	public $biaya;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
