<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ReceivingOrderRecord extends TActiveRecord
{
	const TABLE='tbt_receiving_order';

	public $id;
	public $id_po;
	public $no_document;
	public $no_faktur;
	public $tgl_terima;
	public $catatan;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
