<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ReceivingOrderDetailRecord extends TActiveRecord
{
	const TABLE='tbt_receiving_order_detail';

	public $id;
	public $id_parent;
	public $id_po_detail;
	public $id_barang;
	public $id_satuan;
	public $expired_date;
	public $jumlah;
	public $harga_satuan_besar;
	public $harga_satuan;
	public $discount;
	public $subtotal;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
