<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RekapNeracaDetailRecord extends TActiveRecord
{
	const TABLE='tbt_rekap_neraca_detail';

	public $id;
	public $id_rekap;
	public $nama_akun;
	public $neraca_saldo_debet;
	public $neraca_saldo_kredit;
	public $penyesuaian_debet;
	public $penyesuaian_kredit;
	public $ns_disesuaikan_debet;
	public $ns_disesuaikan_kredit;
	public $laba_rugi_debet;
	public $laba_rugi_kredit;
	public $neraca_debet;
	public $neraca_kredit;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
