<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RekapGajiDetailRecord extends TActiveRecord
{
	const TABLE='tbt_rekap_gaji_detail';

	public $id;
	public $id_rekap;
	public $id_bayar;
	public $id_karyawan;
	public $jml_gaji_dibayarkan;
	public $jns_bayar;
	public $id_bank;
	public $no_ref;
	public $id_coa;
	public $status;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
