<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RekapNeracaDetailRecord extends TActiveRecord
{
	const TABLE='tbt_rekap_neraca_detail';

	public $id;
	public $id_rekap;
	public $kelompok_akun;
	public $nama_akun;
	public $nilai_akun;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
