<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RekapNeracaRecord extends TActiveRecord
{
	const TABLE='tbt_rekap_neraca';

	public $id;
	public $bulan;
	public $tahun;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
