<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RekapGajiDetailRecord extends TActiveRecord
{
	const TABLE='tbt_rekap_gaji_detail';

	public $id;
	public $id_rekap;
	public $id_bayar;
	public $id_karyawan;
	public $gaji_pokok;
	public $tunjangan_natura;
	public $incentive;
	public $tunjangan_jabatan;
	public $tunjangan_komunikasi;
	public $premi_karyawan;
	public $total_gaji;
	public $lembur_lpp_jam;
	public $lembur_lpp_tarif;
	public $lembur_lpp_total;
	public $lembur_lppml_jam;
	public $lembur_lppml_tarif;
	public $lembur_lppml_total;
	public $lembur_lpplk_jam;
	public $lembur_lpplk_tarif;
	public $lembur_lpplk_total;
	public $total_lembur;
	public $mangkir;
	public $terlambat_masuk_kerja;
	public $total_mangkir_terlambat;
	public $total_gaji_kotor;
	public $bpjs_kesehatan;
	public $bpjs_ketenagakerjaan;
	public $pinjaman;
	public $kantin;
	public $koperasi;
	public $total_potongan;
	public $jml_gaji_dibayarkan;
	public $jns_bayar;
	public $id_bank;
	public $no_ref;
	public $id_coa;
	public $status;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
