<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RequestOrderRecord extends TActiveRecord
{
	const TABLE='tbt_request_order';

	public $id;
	public $status;
	public $no_ro;
	public $tgl_ro;
	public $catatan;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
