<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class RequestOrderDetailRecord extends TActiveRecord
{
	const TABLE='tbt_request_order_detail';

	public $id;
	public $status;
	public $id_ro;
	public $id_barang;
	public $id_satuan;
	public $jumlah;
	public $harga_satuan_besar;
	public $harga_satuan;
	public $subtotal;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
