<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ResignEmployeeRecord extends TActiveRecord
{
	const TABLE='tbt_resign_employee';

	public $id;
	public $id_karyawan;
	public $tgl_resign;
	public $kategori_resign;
	public $keterangan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
