<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class SanksiRecord extends TActiveRecord
{
	const TABLE='tbt_sanksi';

	public $id;
	public $id_karyawan;
	public $payroll_id;
	public $tgl_sanksi;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
