<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class SantunanRecord extends TActiveRecord
{
	const TABLE='tbt_santunan';

	public $id;
	public $id_karyawan;
	public $id_payroll;
	public $tgl_santunan;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
