<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ShiftSettingRecord extends TActiveRecord
{
	const TABLE='tbm_shift_setting';

	public $id;
	public $shif;
	public $datang;
	public $pulang;
	public $lama;
	public $waktumakan;
	public $ket;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
