<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class StockOpnameDetailRecord extends TActiveRecord
{
	const TABLE='tbt_stock_opname_detail';

	public $id;
	public $id_stock_opname;
	public $id_barang;
	public $id_satuan;
	public $stok_awal;
	public $stok_akhir;
	public $perbedaan;
	public $status;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
