<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class StockInOutRecord extends TActiveRecord
{
	const TABLE='tbt_stok_in_out';

	public $id;
	public $id_barang;
	public $stok_awal;
	public $stok_in;
	public $nilai_in;
	public $stok_out;
	public $nilai_out;
	public $stok_akhir;
	public $keterangan;
	public $id_transaksi;
	public $jns_transaksi;
	public $tgl;
	public $wkt;
	public $username;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
