<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class StockOpnameRecord extends TActiveRecord
{
	const TABLE='tbt_stock_opname';

	public $id;
	public $no_stock_opname;
	public $tgl_stock_opname;
	public $wkt_stock_opname;
	public $jumlah_barang;
	public $username;
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
