<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class TbsOrderRecord extends TActiveRecord
{
	const TABLE='tbt_tbs_order';

	public $id;
	public $no_tbs_order;
	public $id_barang;
	public $id_pemasok;
	public $id_jenis_kendaraan;
	public $no_polisi;
	public $tgl_transaksi;
	public $wkt_transaksi;
	public $bruto;
	public $tarra;
	public $netto_1;
	public $potongan;
	public $hasil_potongan;
	public $netto_2;
	public $jml_tandan;
	public $komidel;
	public $id_komidel;
	public $status;
	public $deleted;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
