<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class TbsOrderDetailRecord extends TActiveRecord
{
	const TABLE='tbt_tbs_order_detail';

	public $id;
	public $id_tbs_order;
	public $id_jenis_kendaraan;
	public $no_polisi;
	public $bruto;
	public $tarra;
	public $netto_1;
	public $potongan;
	public $hasil_potongan;
	public $netto_2;
	public $jml_tandan;
	public $komidel;
	public $id_komidel;
	public $jumlah_bongkar;
	public $subtotal_spsi;
	public $harga;
	public $subtotal_tbs;
	public $fee;
	public $subtotal_fee;
	public $ppn;
	public $pph;
	public $total_tbs_order;
	public $deleted;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
