<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class TransaksiLuarRecord extends TActiveRecord
{
	const TABLE='tbt_transaksi_luar';

	public $id;
	public $sumber_transaksi;
	public $jns_transaksi;
	public $tgl_transaksi;
	public $wkt_transaksi;
	public $keterangan;
	public $jml_transaksi;
	public $st_posting;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
