<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='tbd_user';

	public $username;
	public $password;
	public $nama;
	public $group;
	public $status;
	public $tgl_create;
	public $wkt_create;
	public $tgl_log;
	public $wkt_log;
	public $st_log;
	public $ssid;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
