<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class UserGroupRecord extends TActiveRecord
{
	const TABLE='tbm_user_group';

	public $id;
	public $nama;

	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
