<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class UserMenuGroupRecord extends TActiveRecord
{
	const TABLE='tbm_user_menu_group';

	public $id;
	public $user_group_id;
	public $menu_id;
	public $st;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
